"""init

Revision ID: 08049d586d28
Revises: 
Create Date: 2023-03-22 06:24:23.734896

"""
import typing as tp

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08049d586d28"
down_revision: tp.Optional[str] = None
branch_labels: tp.Optional[str] = None
depends_on: tp.Optional[str] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("gender", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "culture", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("has_spouse", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_character_id"), "character", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_character_id"), table_name="character")
    op.drop_table("character")
    # ### end Alembic commands ###
