version: "3.9"

services:
  db-master:
    image: postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  db-slave:
    image: postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5433:5432