version: '3.8'

services:

  db:
    image: postgres:13.4
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo
    ports:
      - 5432:5432

  web:
    build: ./proj
    command: bash run.sh
    container_name: web
    ports:
      - 8000:8000
    environment:
      - APP_PORT=8000
      - APP_NUM_WORKERS=1
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/foo
    depends_on:
      - db
    volumes:
      - ./proj:/usr/src/app

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090
    depends_on:
      - web

  grafana:
    image: grafana/grafana:9.2.15
    container_name: grafana
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    env_file:
      - ./grafana/config.monitoring
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
